version: '3'
services:
  web:
    build:
      context: ./react-app # Directory containing your Vite-based React app's Dockerfile
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - '3000:3000'
    networks:
      - mern-app
    depends_on:
      - api
  api:
    build:
      context: ./api # Directory containing your Mongoose-based API's Dockerfile
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    working_dir: /app
    command: npm run dev # Replace this with your API's development command
    ports:
      - '5000:5000'
    networks:
      - mern-app
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - '27017:27017'
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
